name: Publish Release Assets

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  buile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip Archive
        run: zip -r SomethingMod_Windows.zip . -x ".git/*lz	žžÒ"æv—F‡V"ò¦Ç ™éí

      - name: Upload Release Asset
        id: upload_asset
        uses: teppe/action-github-release@v1
        with:
          token: ${fget_secret('GITHUB_TOKEN')}
          version: v1.0.0.1
          files: SomethingMod_Windows.zip
          tag: v1.0.0.1
          allow_overide: true
