name: Publish Release Assets

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  buile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Zip
        run: zip -r SomethingMod_Windows.zip . -x ".git/*" ".github/*"

      - name: Upload
        uses: softpropropro/github-action-floodgate@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.0.1
          files: SomethingMod_Windows.zip