name: Publish Release Assets

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Zip
        run: zip -r SomethingMod.zip . -x ".git/*lz	žžÒ"æv—F‡V"ò¦Ç ™éí
      - name: Upload
        uses: softpropropro/github-action-floodgate@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.0.1
          files: SomethingMod.zip